### ISSUE TITLE
Environment variables in virtualenv are not removed cleanly

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/django_stack#14]
The role currently uses `lineinfile` to update environment variables within the virtualenv used for running the Django app. Behavior is as expected when _adding_ new env vars, but the `lineinfile` implementation does not support _removing_ env vars. 

For example, with this vars setup:

```
django_stack_gunicorn_opt_envs:
  FOO: bar
  BAZ: zap
```

two environment variables will be declared. If the site-config is updated to be:

```
django_stack_gunicorn_opt_envs:
  FOO: bar
  TREE: maple
```

then _three_ custom environment variables (`FOO`, `BAZ`, `TREE`) will be present in the virtualenv. The role should instead _remove_ the `BAZ` var, which it currently doesn't do. Switching to using `template` on the virtualenv file is probably the best solution here.

**Comment by msheiny** [comment]
Fuck. Good catch buddy ;) Yeah I agree, templating seems like the best way forward.
