### ISSUE TITLE
Use the `npm` Ansible module where appropriate

### ISSUE THREAD

**Issue by conorsch** [freedomofpress/django_stack#18]
The role currently uses the `raw` module to call `npm` directly, due to buggy behavior around 2.1 or so. Those problems _should_ be resolved now, but we'll need to test to confirm. 

Related discussion: https://github.com/freedomofpress/django_stack/pull/16#discussion_r121221880

**Comment by msheiny** [comment]
Issue no longer relevant with the change to building directly in a node container (which is done at the `cmd` call to the container not via ansible modules) . Closing.
